"""Password hashing stays compatible with hashes stored earlier through passlib."""

from __future__ import annotations

from app import security

# Generated by passlib 1.7.4 (pbkdf2_sha256), the library the app used before.
_PASSLIB_1000 = "$pbkdf2-sha256$1000$J6Q05pyTMqb03tt7L8WY0w$x22kVkS/Qz/n9oq8qzcjihFtfY8.gpiY/8sbgKqR7o8"
_PASSLIB_310000 = "$pbkdf2-sha256$310000$tXbOOcc45zwHIMSYUwrBeA$yiGP4IwvCYGxEI8d5kxdWHrXeirFcfXAaernLF2iRr0"


def test_verifies_hashes_created_by_passlib():
    assert security.verify_password("Heslo123!", _PASSLIB_1000)
    assert not security.verify_password("Heslo123?", _PASSLIB_1000)
    assert security.verify_password("TestPass123", _PASSLIB_310000)


def test_hash_roundtrip_and_format():
    h = security.hash_password("Správne heslo ✓")
    assert h.startswith(f"$pbkdf2-sha256${security.PASSWORD_HASH_ROUNDS}$")
    assert security.verify_password("Správne heslo ✓", h)
    assert not security.verify_password("Spravne heslo", h)
    assert security.hash_password("x") != security.hash_password("x")   # random salt


def test_needs_rehash_only_for_weaker_hashes(monkeypatch):
    monkeypatch.setattr(security, "PASSWORD_HASH_ROUNDS", 5000)
    assert security.needs_rehash(_PASSLIB_1000)
    assert not security.needs_rehash(_PASSLIB_310000)
    assert not security.needs_rehash("not-a-hash")


def test_malformed_hashes_are_rejected_not_raised():
    for bad in ("", "plain", "$pbkdf2-sha256$abc$x$y", "$pbkdf2-sha256$1000$!!$!!", "$bcrypt$12$x", None,
                "$pbkdf2-sha256$1000$J6Q05pyTMqb03tt7L8WY0w$short"):
        assert security.verify_password("x", bad) is False
