"""Premium PDF report: portfolio P&L, personal forecast accuracy, duels and recent alerts."""

from __future__ import annotations

import io
from xml.sax.saxutils import escape
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy.orm import Session

from app.config import QUANT_LABEL
from app.models import PriceAlert, User
from app.services.account_data import personal_stats
from app.services.alerts import fmt_price
from app.services.tracker import summary

_STYLE = TableStyle([
    ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9), ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
    ("ALIGN", (1, 0), (-1, -1), "RIGHT"), ("BOTTOMPADDING", (0, 0), (-1, -1), 5), ("TOPPADDING", (0, 0), (-1, -1), 5),
])


def _table(header, rows, widths):
    table = Table([header, *rows], colWidths=widths, repeatRows=1)
    table.setStyle(_STYLE)
    return table


def _pct(value) -> str:
    return "—" if value is None else f"{value:+.2f}%"


def _money(value: float) -> str:
    return fmt_price(value) if value >= 0 else "-" + fmt_price(-value)


def _num(value) -> str:
    return "—" if value is None else f"{value}%"


def build_report(db: Session, user: User) -> bytes:
    styles = getSampleStyleSheet()
    h1, h2, body, small = styles["Title"], styles["Heading2"], styles["BodyText"], styles["Italic"]
    now = datetime.now(timezone.utc)
    story = [Paragraph("AI Crypto Analytics — Premium report", h1),
             Paragraph(f"{escape(user.username)} · {now:%d %b %Y, %H:%M} UTC", body), Spacer(1, 6 * mm)]

    portfolio = summary(db, user)
    story.append(Paragraph("Portfolio", h2))
    if portfolio["positions"]:
        t = portfolio["total"]
        story.append(Paragraph(f"Value {fmt_price(t['value'])} · cost {fmt_price(t['cost'])} · "
                               f"P&amp;L {_money(t['pnl'])} ({_pct(t['pnl_pct'])}) · risk {portfolio['risk']['score'] or '—'}/10", body))
        story.append(Spacer(1, 3 * mm))
        story.append(_table(["Coin", "Amount", "Avg. buy", "Price", "Value", "P&L", "Share"],
                            [[r["coin"], f"{r['amount']:g}", fmt_price(r["avg_buy_price"]),
                              fmt_price(r["price"]) if r["price"] else "—", "—" if r["value"] is None else _money(r["value"]),
                              _pct(r["pnl_pct"]), "—" if r["allocation_pct"] is None else f"{r['allocation_pct']}%"] for r in portfolio["positions"]],
                            [22 * mm, 24 * mm, 26 * mm, 26 * mm, 28 * mm, 24 * mm, 18 * mm]))
    else:
        story.append(Paragraph("No tracked positions yet.", body))

    stats = personal_stats(db, user.id)
    story += [Spacer(1, 6 * mm), Paragraph("Your forecast accuracy", h2)]
    if stats["total_evaluated"]:
        story.append(Paragraph(f"{stats['total_evaluated']} checked forecasts · direction right "
                               f"{_num(stats['direction_hit_pct'])} · duels {stats['duels']['wins']} won, "
                               f"{stats['duels']['losses']} lost", body))
        story.append(Spacer(1, 3 * mm))
        story.append(_table(["AI model", "Checked", "Direction hit", "Avg. accuracy", "Beats naive"],
                            [["Free statistical model" if r["key"] == QUANT_LABEL else r["key"], r["evaluated"],
                              _num(r["direction_hit_pct"]), _num(r["avg_accuracy_pct"]), _num(r["beats_baseline_pct"])]
                             for r in stats["by_provider"]],
                            [56 * mm, 24 * mm, 32 * mm, 32 * mm, 26 * mm]))
    else:
        story.append(Paragraph("None of your forecasts has been checked yet.", body))

    fired = (db.query(PriceAlert).filter(PriceAlert.user_id == user.id, PriceAlert.triggered_at.isnot(None))
             .order_by(PriceAlert.triggered_at.desc()).limit(10).all())
    story += [Spacer(1, 6 * mm), Paragraph("Recent alerts", h2)]
    if fired:
        story.append(_table(["When (UTC)", "Alert", "Condition", "Value"],
                            [[a.triggered_at.strftime("%d %b %H:%M"), f"{a.coin} · {a.kind}",
                              f"{a.direction} {a.target_price:g}", f"{a.triggered_price:g}"] for a in fired],
                            [36 * mm, 44 * mm, 50 * mm, 40 * mm]))
    else:
        story.append(Paragraph("No alerts fired yet.", body))

    story += [Spacer(1, 8 * mm), Paragraph("Estimates only, not financial advice. Generated by aicryptopredictor.netlify.app", small)]
    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=16 * mm, rightMargin=16 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
                      title="AI Crypto Analytics report", author="AI Crypto Analytics").build(story)
    return buf.getvalue()
